//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Levels: [
      { levelNumber: 1, id: 46 },
      { levelNumber: 2, id: 73 },
      { levelNumber: 3, id: 69 },
      { levelNumber: 4, id: 51 },
      { levelNumber: 5, id: 39 },
    ],
  },
};
export default data;
